version: 2
jobs:
  one:
    docker:
      - image: circleci/nodes:4.8.2
    steps:
      - checkout
  two:
   docker:
      - image: circleci/nodes:4.8.2

    steps:
      - checkout
      
workflows:
  version: 2
  
  my_workflows:
    jobs:
      - one
      - two
