version: 2
jobs:
  one:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
  one
   docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo a more familiar hello.
          
workflows:
version: 2
  one_and_two:
    jobs:
      - one
      - two
