version: 2
jobs:
  one:
    docker:
      - image: debian:stretch
    steps:
      - checkout
  two:
   docker:
      - image: debian:stretch
    steps:
      - checkout
      
workflows:
  version: 2
  
  my_workflows:
    jobs:
      - one
      - two
