version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
  build2:
   docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      
workflows:
  version: 2
  
my_workflows:
  jobs:
    - build
    - build2
